version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - doxygen
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - doxygen
      - doxysphinx build doc/ doc/build Doxyfile

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt