name: CI
on: push
jobs:
  build:
    name: Build
    runs-on: [ubuntu-24.04]
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        # TODO: Add stm32l432xc-build-test, and other cross-compilation stuff later.
        preset: [linux]
        assert_setting: [ECU_DISABLE_ASSERTS=OFF, ECU_DISABLE_ASSERTS=ON]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cmake -D${{matrix.assert_setting}} --preset ${{matrix.preset}}
        cmake --build --clean-first --preset ${{matrix.preset}} --target ecu

  documentation:
    name: Documentation
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install -y doxygen graphviz
        pip install -r requirements.txt --break-system-packages
    - name: Generate documentation
      run: |
        sudo apt install -y doxygen graphviz
        cmake --build --preset linux --target sphinx

  unit_test:
    name: Unit Test
    needs: build
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install -r requirements.txt --break-system-packages
    - name: Run tests
      run: |
        cmake --build --preset linux --target unit_test_exe
        ctest --preset unit_test
    - name: Generate code coverage report
      run: cmake --build --preset linux --target gcovr
    - name: Upload code coverage report
      uses: codecov/codecov-action@v5
      with:
        directory: ./bin/coverage/
        disable_telem: true
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
      